# Generated by Django 5.0.3 on 2024-05-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("progetto_macchine", "0004_alter_machineimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machineimage",
            name="image",
            field=models.ImageField(upload_to="images"),
        ),
    ]
