# Generated by Django 5.0.3 on 2024-05-10 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("progetto_macchine", "0005_alter_machineimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machineimage",
            name="image",
            field=models.ImageField(upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="machineimage",
            name="machine",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="progetto_macchine.machine",
            ),
        ),
    ]
